### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by HuiruZhong** [drewpendergrass/CHEEREIO#17]
In the GC_to_sat_levels function at line 350 of tropomi_tools.py, the condition if species == "CO" or "NO2": should be written as if species == "CO" or species == "NO2":. Otherwise, it will always return True, since 'NO2' is treated as a non-empty string. If the species is CH4, this could cause GC_on_sat = np.concatenate(GC_on_sat_list, axis=0) to return an empty list when there aren't many observations.

**Comment by HuiruZhong** [comment]
When it comes to East Asia, TROPOMI had no satellite data from July 26th to August 29th, 2022

**Comment by drewpendergrass** [comment]
Thanks for pointing out the GC_to_sat_levels bug -- this has actually already been fixed in the dev branch, and will be fixed in version 1.4 when it is released. In the meantime, rewrite the line as you mentioned and it will speed up run times for methane and fix the empty list error. TROPOMI operational data is missing in that period and in a similar time of year in 2023. This is apparently because of missing VIIRS data.
