### ISSUE TITLE
Conda env create fail using cheereio.yaml

### ISSUE THREAD

**Issue by YunxiaoT** [drewpendergrass/CHEEREIO#8]
It's on Cannon Cluster.
Error message here:
```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - libgfortran5==11.1.0=h6c583b3_0
  - libgfortran-ng==11.1.0=h69a702a_0
```

**Comment by drewpendergrass** [comment]
Packages!! They're always so difficult.

- As we discussed via email, you can try updating the various packages in the YAML file. Hopefully this works.
- Since this is a gfortran issue specifically, try building the environment after activating the cheereio.env file for Cannon. It may be an issue of non-conda dependencies and builds.
